---
  - name: Install oracle JDK
    apt: pkg=python-software-properties state=latest
    apt_repository: repo='ppa:webupd8team/java' state=present

  - name: Update Repositories cache
    apt: update-cache=yes cache_valid_time=3600

  - name: Install packages
    apt: pkg={{item}} state=latest
    with_items:
      - python-dev
      - python-pip
      - curl
      - oracle-java7-installer

  # - name: Export JAVA_HOME
  #   lineinfile: dest="/etc/environment" line="JAVA_HOME="  create=true
